service: cdn-php

params:
    default:
        storage_driver: s3
        cache_ttl: 31536000

    prod:
        app_debug: 0
        log_level: info
        allowed_domains: ${ssm:/cdn-php/allowed-domains}
        s3_bucket: ${ssm:/cdn-php/s3-bucket}
        s3_endpoint: ${ssm:/cdn-php/s3-endpoint}
        s3_region: ${ssm:/cdn-php/s3-region}
        s3_access_key: ${ssm:/cdn-php/s3-access-key}
        s3_secret_key: ${ssm:/cdn-php/s3-secret-key}

    dev:
        app_debug: 1
        log_level: debug
        allowed_domains: ${ssm:/cdn-php/dev/allowed-domains}
        s3_bucket: ${ssm:/cdn-php/dev/s3-bucket}
        s3_endpoint: ${ssm:/cdn-php/dev/s3-endpoint}
        s3_region: ${ssm:/cdn-php/dev/s3-region}
        s3_access_key: ${ssm:/cdn-php/dev/s3-access-key}
        s3_secret_key: ${ssm:/cdn-php/dev/s3-secret-key}

provider:
    name: aws
    region: eu-west-3
    apiGateway:
        binaryMediaTypes:
            - '*/*'
    environment:
        BREF_BINARY_RESPONSES: '1'

plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions

functions:
    main:
        handler: public/index.php
        description: 'CDN PHP'
        runtime: php-83-fpm
        layers:
            - ${bref-extra:imagick-php-83}
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'
            - schedule:
                rate: rate(5 minutes)
                input:
                    warmer: true
        environment:
            APP_DEBUG: ${param:app_debug}
            CACHE_TTL: ${param:cache_ttl}
            STORAGE_DRIVER: ${param:storage_driver}
            S3_PATH_STYLE_ENDPOINT: 1
            ALLOWED_DOMAINS: ${param:allowed_domains}
            S3_BUCKET: ${param:s3_bucket}
            S3_ENDPOINT: ${param:s3_endpoint}
            S3_REGION: ${param:s3_region}
            S3_ACCESS_KEY: ${param:s3_access_key}
            S3_SECRET_KEY: ${param:s3_secret_key}
            LOG_STREAM: php://stderr
            LOG_LEVEL: ${param:log_level}
            IMAGE_COMPRESSION: ${ssm:/cdn-php/image-compression}

package:
    patterns:
        - '!.cache/**'
        - '!.idea/**'
        - '!.github/**'
        - '!build/**'
        - '!docker/**'
        - '!tests/**'
        - '!.editorconfig'
        - '!.env.local'
        - '!.gitignore'
        - '!composer.json'
        - '!composer.lock'
        - '!LICENSE'
        - '!Makefile'
        - '!phpcs.xml'
        - '!phpmd-ruleset.xml'
        - '!phpstan.neon'
        - '!phpunit.xml'
        - '!README.md'
        - '!serverless.yml'
