services:
    # PHP Container for dev
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        env_file:
            - .env
        environment:
            HANDLER: public/index.php
            BREF_BINARY_RESPONSES: 1
        ports: [ '${CDN_PHP_PORT:-8000}:8000' ]
        volumes:
            - ..:/var/task
        restart: "no"

    # Open-source S3
    minio:
        image: minio/minio
        command: server --address ":9000" --console-address ":9001" /data
        working_dir: /data
        volumes:
            - ../.cache/driver/s3:/data
        ports:
            - "${MINIO_PORT:-9000}:9000"
            - "${MINIO_CONSOLE_PORT:-9001}:9001"
        environment:
            MINIO_ROOT_USER: ${S3_ACCESS_ID}
            MINIO_ROOT_PASSWORD: ${S3_ACCESS_SECRET}

    minio_mc:
        image: minio/mc
        environment:
            MC_HOST_local: http://${S3_ACCESS_ID}:${S3_ACCESS_SECRET}@minio:9000
