name: Code quality

on:
    push:
        branches:
            - '**'
            - '!main'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    composer:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                    key: composer-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-
                    path: vendor

            -   name: Install PHP with extension
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    extensions: bcmath, gd, imagick

            -   name: Install composer dependencies
                uses: php-actions/composer@v6
                with:
                    interaction: no
                    dev: yes
                    php_version: "8.3"
                    version: 2
                    args: --optimize-autoloader --no-scripts --ignore-platform-reqs

    phpcs:
        runs-on: ubuntu-latest

        needs: [composer]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                    key: composer-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-
                    path: vendor

            -   name: PHP Code Sniffer
                run: make test-phpcs

    phpstan:
        runs-on: ubuntu-latest

        needs: [composer]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install PHP with extension
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    extensions: bcmath, gd, imagick

            -   name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                    key: composer-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-
                    path: vendor

            -   name: PHPStan
                run: make test-phpstan

    phpmd:
        runs-on: ubuntu-latest

        needs: [composer]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install PHP with extension
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    extensions: bcmath, gd, imagick

            -   name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                    key: composer-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-
                    path: vendor

            -   name: PHP Mess Detector
                run: make test-phpmd

    phpunit:
        runs-on: ubuntu-latest

        needs: [composer]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install PHP with extension
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    extensions: bcmath, gd, imagick

            -   name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                    key: composer-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-
                    path: vendor

            -   name: PHPUnit
                run: make test-phpunit

    security:
        runs-on: ubuntu-latest

        needs: [composer]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install PHP with extension
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    extensions: bcmath, gd, imagick

            -   name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                    key: composer-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-
                    path: vendor

            -   name: Audit composer dependencies
                uses: php-actions/composer@v6
                with:
                    interaction: no
                    dev: yes
                    php_version: "8.3"
                    version: 2
                    command: audit
