name: Deploy Lambda

on:
    push:
        tags:
            - '**'

    workflow_dispatch:

jobs:
    deploy-lambda:
        runs-on: ubuntu-latest

        timeout-minutes: 15

        concurrency: deploy-prod # Avoid deploying concurrently

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    coverage: none
                    # Install the Bref CLI as a global tool
                    tools: bref/cli

            -   name: Install composer dependencies
                uses: php-actions/composer@v6
                with:
                    interaction: no
                    dev: no
                    php_version: "8.3"
                    version: 2
                    args: --optimize-autoloader --no-scripts --ignore-platform-reqs

            -   name: Add Bref Cloud team
                run: |
                    echo "bref:" >> serverless.yml
                    echo "    team: babeuloula" >> serverless.yml

            -   run: bref deploy --env=prod
                env:
                    BREF_TOKEN: ${{ secrets.BREF_TOKEN }}
